feat: disable months in the past
eventink/calendar pull request #1
Opened 2018-04-14 16:45 UTC by christianrank

2018-04-16 08:57 UTC, wwwbruno approved these changes

2018-04-16 09:24 UTC, emrox commented
you forgot to add the new props to the `propTypes`

2018-04-16 09:28 UTC, emrox commented
adding some tests for the new props would be good

2018-04-17 14:36 UTC, emrox requested changes

2018-04-17 14:36 UTC, emrox commented on tests/Calendar.spec.jsx
> +    it('render disableMonthsInPast true correctly', () => {
you could group them within an `describe` block for better readability

2018-04-17 14:36 UTC, emrox commented on tests/Calendar.spec.jsx
> +      expect(wrapper.find('.rc-calendar-prev-year-btn.disabled').length).toBe(1);
there is the `.toHaveLength(number)` matcher you could use
https://facebook.github.io/jest/docs/en/expect.html

2018-04-17 14:42 UTC, christianrank commented on tests/Calendar.spec.jsx
> +    it('render disableMonthsInPast true correctly', () => {
cfd5a2f

2018-04-17 14:42 UTC, christianrank commented on tests/Calendar.spec.jsx
> +      expect(wrapper.find('.rc-calendar-prev-year-btn.disabled').length).toBe(1);
cfd5a2f

2018-04-17 14:48 UTC, emrox commented on tests/Calendar.spec.jsx
> +      expect(wrapper.find('.rc-calendar-prev-year-btn.disabled').length).toBe(1);
👍🏻

2018-04-17 14:53 UTC, emrox approved these changes

2018-04-17 16:01 UTC, merged